name: Publish Typedoc to Github Pages
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '21'
          cache: 'npm'
      - run: corepack enable yarn
      - run: yarn install
      - run: git checkout -b typedoc
      - run: git push --set-upstream origin typedoc
      - run: yarn typedoc
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: actions4git/add-commit-push@v1
        with:
          commit-message: 'Update typedoc to commit ${{ steps.vars.outputs.sha_short }}'